### ISSUE TITLE
Crashes on 1.18 when disabling a module

### ISSUE THREAD

**Issue by sleepingdragoninn** [Draconizations/switchy-teleport#2]
Likely related to `Text.translatable` being `new TranslatableText` in 1.18.

`org.quiltmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2561.method_43471(java.lang.String)'`

**Comment by Draconizations** [comment]
Forgot to close this yesterday!
